name: CI | Beta Release

on:
  schedule:
    - cron: '6 * * * *'
  push: {}

jobs:
  modrinth_verify:
    name: Step 0 | Modrinth
    uses: ./.github/workflows/reusable-modrinth_verify.yml

  para_cache:
    name: Step 0 | Cache
    uses: ./.github/workflows/reusable-cache.yml
    with:
      cache_key: beta-cache
    secrets:
      PARATRANZ_API_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

  github_matrix:
    name: Step 1 | GitHub Matrix
    needs: [ modrinth_verify, para_cache ]
    if: ${{ needs.modrinth_verify.outputs.is-same-date != 'true' }}
    # if: ${{ needs.para_cache.outputs.cache-hit != 'true' && needs.modrinth_verify.outputs.is-same-date != 'true' }}
    uses: ./.github/workflows/reusable-github_matrix.yml

  para_paraify:
    name: Step 2 | Paraify Build ${{ matrix.mc_version }}
    needs: [ github_matrix ]
    strategy:
      matrix: ${{ fromJson(needs.github_matrix.outputs.matrix-data) }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      mc_version: ${{ matrix.mc_version }}
      pack_format: ${{ matrix.mc_pack_format }}
      pack_supported_format_min: ${{ matrix.mc_supported_formats_min }}
      pack_supported_format_max: ${{ matrix.mc_supported_formats_max }}
    secrets:
      PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

  para_r2:
    name: Step 3 | R2 Upload
    needs: [ para_paraify ]
    uses: ./.github/workflows/reusable-r2.yml
    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
      CLOUDFLARE_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }} 
      CLOUDFLARE_SECRET_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}

  para_discord:
    name: Step 4 | Discord Notification
    needs: [ para_r2 ]
    uses: ./.github/workflows/reusable-dcwebhook.yml
    secrets:
      PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
