name: Reusable | Modrinth Publish

on: 
  workflow_call:
    inputs:
      mc_version:
        description: "Minecraft Version"
        type: string
        required: true
      modrinth_game_version:
        description: "Modrinth MC Version Range"
        type: string
        required: true
      modrinth_summary:
        description: "Modrinth Summary"
        type: string
        required: true
    secrets:
        MODRINTH_TOKEN:
          description: "Modrinth API Token"
          required: true

jobs:
  modrinth_publish:
    name: Modrinth Publish
    runs-on: ubuntu-latest
    steps:
      - name: GitHub - Generate Date
        id: date
        run: |
          TODAY=$(TZ="Asia/Taipei" date +%Y%m%d)
          TODAY_DASH=$(TZ="Asia/Taipei" date +%Y-%m-%d)
          echo "today=$TODAY" >> "$GITHUB_OUTPUT"
          echo "today_dash=$TODAY_DASH" >> "$GITHUB_OUTPUT"

      - name: GitHub - Download ParaTranslationPack
        uses: actions/download-artifact@v4
        with:
          name: ParaTranslationPack-${{ inputs.mc_version }}

      - name: GitHub - Rename ParaTranslationPack
        run: |
          mv pack.zip ParaTranslationPack-${{ inputs.mc_version }}.zip

      - name: Modrinth - Publish ${{ inputs.mc_version }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 7DO0XWSK
          modrinth-unfeature-mode: subset
          name: Para 翻譯包 ${{ inputs.mc_version }}｜${{ steps.date.outputs.today_dash }}
          version: ${{ inputs.mc_version }}-${{ steps.date.outputs.today }}
          version-type: release
          changelog: |
            ${{ inputs.modrinth_summary }}
          loaders: minecraft
          game-versions: ${{ inputs.modrinth_game_version }}
          files: |
            ParaTranslationPack-${{ inputs.mc_version }}.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
