name: Reusable | GitHub Matrix

on:
  workflow_call:
    outputs:
      matrix-data:
        description: "GitHub Matrix data"
        value: ${{ jobs.github_matrix.outputs.gh_matrix }}

env:
  LOGURU_LEVEL: "INFO"

jobs:
  github_matrix:
    name: GitHub Matrix
    runs-on: ubuntu-latest
    outputs:
      gh_matrix: ${{ steps.gh_matrix.outputs.matrix_data }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true

      - name: Run GitHub Matrix Generate
        id: gh_matrix
        run: |
          uv run github_matrix
