name: Reusable | Discord Webhook

on: 
  workflow_call:
    secrets:
      PARATRANZ_TOKEN:
        description: "ParaTranz API Token"
        required: true
      DISCORD_WEBHOOK_URL:
        description: "Discord Webhook URL"
        required: true
      DISCORD_WEBHOOK_ID:
        description: "Discord Webhook ID"
        required: true

env:
  LOGURU_LEVEL: "INFO"
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  DC_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  DC_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}

jobs:
  discordwebhook:
    name: Discord Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true
    
      - name: Run Discord Webhook
        run: |
          uv run webhook_update
