name: Reusable | Modrinth Summary

on: 
  workflow_call:
    outputs:
      modrinth-summary:
        description: "Modrinth Summary"
        value: ${{ jobs.modrinth_summary.outputs.summary }}
    secrets:
        PARATRANZ_TOKEN:
          description: "ParaTranz API Token"
          required: true

env:
  LOGURU_LEVEL: "INFO"
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}

jobs:
  modrinth_summary:
    name: Modrinth Summary
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.modrinth_summary.outputs.summary }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true

      - name: Run Modrinth Verify Script
        id: modrinth_summary
        run: |
          uv run para_summary
