name: Reusable | Modrinth Summary

on: 
  workflow_call:
    outputs:
      modrinth-summary:
        description: "Modrinth Summary"
        value: ${{ jobs.modrinth_summary.outputs.summary }}
    secrets:
        PARATRANZ_TOKEN:
          description: "ParaTranz API Token"
          required: true

env:
  python_version: "3.13"
  poetry_version: "2.1.1"
  LOGURU_LEVEL: "INFO"

jobs:
  modrinth_summary:
    name: Modrinth Summary
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.modrinth_summary.outputs.summary }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ env.python_version }}

      - name: Setup Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: ${{ env.poetry_version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Cache Poetry Dependencies
        id: poetry_dependencies_cache
        uses: actions/cache@v4.2.0
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Poetry install dependencies
        if: ${{ steps.poetry_dependencies_cache.outputs.cache-hit != 'true' }}
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          poetry install --no-interaction

      - name: Run Modrinth Verify Script
        id: modrinth_summary
        run: |
          poetry run para_summary
