name: Reusable | Para Cache

on: 
  workflow_call:
    inputs:
      cache_key:
        type: string
        required: true
        description: "The name of the cache key."
    outputs:
      cache-hit:
        description: "Cache hit status"
        value: ${{ jobs.cache.outputs.cache-hit }}
    secrets:
      PARATRANZ_API_TOKEN:
        required: true
        description: "Paratranz API Token"

env:
  PARATRANZ_API_TOKEN: ${{ secrets.PARATRANZ_API_TOKEN }}
  LOGURU_LEVEL: "INFO"

jobs:
  cache:
    name: Para Cache
    outputs:
      cache-hit: ${{ steps.para_cache.outputs.cache-hit }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true

      - name: Restore Cache
        uses: actions/cache/restore@v4.2.0
        with:
          path: .cache/paratranz_id_cache.txt
          key: ${{ inputs.cache_key }}-

      - name: Run Cache Script
        run: |
          uv run para_cache_id

      - name: Save Cache
        id: para_cache
        uses: actions/cache@v4.2.0
        with:
          path: .cache/paratranz_id_cache.txt
          key: ${{ inputs.cache_key }}-${{ hashFiles('.cache/paratranz_id_cache.txt') }}
