name: Reusable | R2

on: 
  workflow_call:
    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        description: "Cloudflare Account ID"
        required: true
      CLOUDFLARE_BUCKET_NAME:
        description: "Cloudflare Bucket Name"
        required: true
      CLOUDFLARE_ACCESS_KEY:
        description: "Cloudflare Access Key"
        required: true
      CLOUDFLARE_SECRET_KEY:
        description: "Cloudflare Secret Key"
        required: true

jobs:
  para_r2:
    name: R2
    runs-on: ubuntu-latest
    steps:
      - name: Setup s3cmd
        uses: s3-actions/s3cmd@v1.9.0
        with:
          provider: cloudflare
          account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          access_key: ${{ secrets.CLOUDFLARE_ACCESS_KEY }}
          secret_key: ${{ secrets.CLOUDFLARE_SECRET_KEY }}

      - name: Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: ParaTranslationPack-*

      - name: Move and rename files based on folder name
        run: |
            for dir in */; do
            if [ -d "$dir" ]; then
                base=$(basename "$dir")
                mv "$dir"/pack.zip "$base".zip
                rm -r "$dir"
            fi
            done
            ls -R

      - name: Upload to R2
        run: |
          cdt=$(TZ="Asia/Taipei" date +"%Y-%m-%d-%H")
          s3cmd put *.zip s3://${{ secrets.CLOUDFLARE_BUCKET_NAME }}/paratranslationpack/$cdt/
