name: Reusable | Modrinth Verify

on: 
  workflow_call:
    outputs:
      is-same-date:
        description: "Check the date is exists on modrinth"
        value: ${{ jobs.modrinth_verify.outputs.is_same_date }}

env:
  LOGURU_LEVEL: "INFO"

jobs:
  modrinth_verify:
    name: Modrinth Verify
    outputs:
      is_same_date: ${{ steps.modrinth_verify.outputs.is_same_date }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.0
        with:
          enable-cache: true

      - name: Run Modrinth Verify Script
        id: modrinth_verify
        run: |
          uv run modrinth_verify_publish
